---
namespace: bnc
name: semaphore
authors:
  - Alexandre Georges <alexandre.georges@bnc.ch> (@mageo)
version: 0.1.0
readme: README.md
description: Ansible collection to interact with Ansible Semaphore API
license_file: LICENSE
dependencies: {}
repository: https://github.com/bnc-ch/bnc.semaphore
