---
namespace: bnc
name: semaphore
authors:
  - Alexandre Georges <alexandre.georges@bnc.ch> (@mageo)
version: 0.0.1
readme: README.md
description: Ansible module to interact with Ansible Semaphore API
license_file: LICENSE
dependencies: {}
repository: https://github.com/bnc-ch/bnc.semaphore
